# Generated by Django 6.0.6 on 2026-06-10 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='learning_goal',
            field=models.CharField(choices=[('general', 'General English'), ('cefr', 'CEFR Levels (A1–C2)'), ('ielts', 'IELTS Preparation')], default='general', max_length=20),
        ),
    ]
