# Generated by Django 6.0.6 on 2026-06-24 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_learning_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_teacher',
            field=models.ForeignKey(blank=True, help_text="Bu studentni qaysi teacher o'ziga biriktirgan", limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_students', to=settings.AUTH_USER_MODEL),
        ),
    ]
