# Generated by Django 6.0.6 on 2026-06-15 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrammarRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('formula', models.CharField(blank=True, help_text='Qoidaning sxemasi, masalan: Subject + V1 + Object', max_length=500)),
                ('explanation', models.TextField(help_text='Qoidani tushuntirish (Markdown)')),
                ('explanation_uz', models.TextField(blank=True, help_text="O'zbekcha tushuntirish (ixtiyoriy)")),
                ('tips', models.TextField(blank=True, help_text='Foydali maslahatlar va eslatmalar')),
                ('common_mistakes', models.TextField(blank=True, help_text='Tez-tez uchraydigan xatolar')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['topic', 'order'],
            },
        ),
        migrations.CreateModel(
            name='GrammarExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.TextField(help_text='Inglizcha misol gap')),
                ('translation', models.TextField(blank=True, help_text="O'zbekcha tarjima")),
                ('highlight', models.CharField(blank=True, help_text='Gap ichidagi muhim qism (frontend bunda bold qiladi)', max_length=200)),
                ('is_incorrect', models.BooleanField(default=False, help_text="Bu — XATO misol (qanday qilmaslik kerakligini ko'rsatish uchun)")),
                ('audio_url', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='grammar.grammarrule')),
            ],
            options={
                'ordering': ['rule', 'order'],
            },
        ),
        migrations.CreateModel(
            name='GrammarTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('category', models.CharField(choices=[('tenses', 'Tenses (Zamonlar)'), ('articles', 'Articles (a/an/the)'), ('pronouns', 'Pronouns (Olmoshlar)'), ('prepositions', 'Prepositions'), ('conditionals', 'Conditionals (Shart gaplari)'), ('modals', 'Modal Verbs'), ('passive', 'Passive Voice'), ('reported', 'Reported Speech'), ('clauses', 'Relative Clauses'), ('word_order', 'Word Order'), ('questions', 'Questions & Negatives'), ('comparatives', 'Comparatives & Superlatives'), ('quantifiers', 'Quantifiers (some/any/much/many)'), ('phrasal_verbs', 'Phrasal Verbs'), ('other', 'Boshqa')], db_index=True, default='other', max_length=20)),
                ('cefr_level', models.CharField(blank=True, choices=[('A1', 'A1 — Beginner'), ('A2', 'A2 — Elementary'), ('B1', 'B1 — Intermediate'), ('B2', 'B2 — Upper-Intermediate'), ('C1', 'C1 — Advanced'), ('C2', 'C2 — Proficient')], db_index=True, max_length=2)),
                ('short_description', models.CharField(blank=True, help_text='Qisqacha tushuntirish (1 jumla)', max_length=300)),
                ('description', models.TextField(blank=True, help_text="To'liq tushuntirish (Markdown)")),
                ('icon', models.CharField(blank=True, max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'order', 'title'],
                'indexes': [models.Index(fields=['category', 'cefr_level'], name='grammar_gra_categor_e3d274_idx')],
            },
        ),
        migrations.AddField(
            model_name='grammarrule',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='grammar.grammartopic'),
        ),
        migrations.CreateModel(
            name='LessonGrammar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_main_topic', models.BooleanField(default=False, help_text='Shu darsning asosiy grammar mavzusi')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_grammar', to='content.lesson')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_appearances', to='grammar.grammartopic')),
            ],
            options={
                'ordering': ['lesson', 'order'],
            },
        ),
        migrations.AddIndex(
            model_name='grammarrule',
            index=models.Index(fields=['topic', 'order'], name='grammar_gra_topic_i_1bdb64_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lessongrammar',
            unique_together={('lesson', 'topic')},
        ),
    ]
