# Generated by Django 6.0.6 on 2026-06-15 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track', models.CharField(choices=[('general', 'General English'), ('cefr', 'CEFR Levels'), ('ielts', 'IELTS Preparation')], db_index=True, max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField(blank=True)),
                ('cefr_level', models.CharField(blank=True, choices=[('A1', 'A1 — Beginner'), ('A2', 'A2 — Elementary'), ('B1', 'B1 — Intermediate'), ('B2', 'B2 — Upper-Intermediate'), ('C1', 'C1 — Advanced'), ('C2', 'C2 — Proficient')], help_text='Faqat CEFR track uchun majburiy', max_length=2)),
                ('ielts_skill', models.CharField(blank=True, choices=[('listening', 'Listening'), ('reading', 'Reading'), ('writing', 'Writing'), ('speaking', 'Speaking')], help_text='Faqat IELTS track uchun', max_length=20)),
                ('icon', models.CharField(blank=True, help_text='Emoji yoki kichik belgi', max_length=10)),
                ('color', models.CharField(blank=True, help_text='Hex yoki tailwind class', max_length=20)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='covers/courses/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['track', 'order', 'title'],
                'indexes': [models.Index(fields=['track', 'is_published'], name='content_cou_track_659790_idx'), models.Index(fields=['track', 'cefr_level'], name='content_cou_track_94c47e_idx')],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='content.course')),
            ],
            options={
                'ordering': ['course', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220)),
                ('lesson_type', models.CharField(choices=[('vocabulary', "So'z o'rganish"), ('grammar', 'Grammatika'), ('reading', "O'qish"), ('listening', 'Tinglash'), ('speaking', 'Gapirish'), ('writing', 'Yozish'), ('mixed', 'Aralash')], default='mixed', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('content', models.TextField(blank=True, help_text='Markdown matn')),
                ('video_url', models.URLField(blank=True)),
                ('audio_url', models.URLField(blank=True)),
                ('estimated_minutes', models.PositiveIntegerField(default=15)),
                ('order', models.PositiveIntegerField(default=0)),
                ('xp_reward', models.PositiveIntegerField(default=10)),
                ('is_published', models.BooleanField(default=False)),
                ('is_premium', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='content.module')),
            ],
            options={
                'ordering': ['module', 'order'],
            },
        ),
        migrations.AddIndex(
            model_name='module',
            index=models.Index(fields=['course', 'order'], name='content_mod_course__07037a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='module',
            unique_together={('course', 'slug')},
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['module', 'order'], name='content_les_module__c210ff_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['is_published'], name='content_les_is_publ_6c24a8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('module', 'slug')},
        ),
    ]
