# Generated by Django 6.0.6 on 2026-06-15 12:07

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        ('exercises', '0001_initial'),
        ('vocabulary', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='Kod (masalan: streak_7_days, words_100)', unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('streak', 'Streak'), ('vocabulary', 'Vocabulary'), ('quiz', 'Quiz'), ('lesson', 'Lesson'), ('xp', 'XP'), ('special', 'Special')], max_length=20)),
                ('icon', models.CharField(blank=True, help_text='Emoji', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='achievements/')),
                ('target_value', models.PositiveIntegerField(default=1, help_text="Maqsadli qiymat (masalan: 7 kun streak, 100 so'z)")),
                ('xp_reward', models.PositiveIntegerField(default=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['category', 'order'],
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'Davom etmoqda'), ('completed', 'Tugatildi'), ('abandoned', 'Tashlab ketildi')], db_index=True, default='in_progress', max_length=20)),
                ('score', models.PositiveIntegerField(default=0, help_text='Olingan ball')),
                ('max_score', models.PositiveIntegerField(default=0, help_text="Maksimal mumkin bo'lgan ball")),
                ('percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('passed', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('time_spent_seconds', models.PositiveIntegerField(default=0)),
                ('xp_earned', models.PositiveIntegerField(default=0)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='exercises.quiz')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(blank=True, help_text='Fill blank / short answer matni')),
                ('is_correct', models.BooleanField(default=False)),
                ('points_earned', models.PositiveIntegerField(default=0)),
                ('time_spent_seconds', models.PositiveIntegerField(default=0)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='exercises.question')),
                ('selected_choices', models.ManyToManyField(blank=True, help_text='Tanlangan variantlar (multiple choice/select uchun)', to='exercises.choice')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='progress.quizattempt')),
            ],
            options={
                'ordering': ['attempt', 'answered_at'],
            },
        ),
        migrations.CreateModel(
            name='Streak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.PositiveIntegerField(default=0, help_text='Hozirgi ketma-ket kunlar')),
                ('longest_streak', models.PositiveIntegerField(default=0, help_text='Eng uzun streak (rekord)')),
                ('last_activity_date', models.DateField(blank=True, null=True)),
                ('streak_started_date', models.DateField(blank=True, null=True)),
                ('freeze_count', models.PositiveIntegerField(default=0, help_text="Mavjud streak freeze'lar soni")),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='streak', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_by', to='progress.achievement')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-earned_at'],
            },
        ),
        migrations.CreateModel(
            name='UserXP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_xp', models.PositiveIntegerField(default=0)),
                ('level', models.PositiveIntegerField(default=1)),
                ('weekly_xp', models.PositiveIntegerField(default=0)),
                ('daily_xp', models.PositiveIntegerField(default=0)),
                ('last_xp_earned_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='xp_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WordProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('learning', "O'rganilmoqda"), ('review', 'Takrorlash'), ('mastered', "O'zlashtirilgan")], db_index=True, default='new', max_length=20)),
                ('ease_factor', models.DecimalField(decimal_places=2, default=Decimal('2.50'), help_text='SM-2 ease factor (1.3 = juda qiyin, 2.5+ = oson)', max_digits=4)),
                ('interval_days', models.PositiveIntegerField(default=0, help_text='Keyingi takrorlashgacha kunlar soni')),
                ('repetitions', models.PositiveIntegerField(default=0, help_text='Ketma-ket muvaffaqiyatli takrorlashlar soni')),
                ('next_review_at', models.DateTimeField(blank=True, db_index=True, help_text='Keyingi takrorlash vaqti', null=True)),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('correct_reviews', models.PositiveIntegerField(default=0)),
                ('lapses', models.PositiveIntegerField(default=0, help_text="Mastered bo'lgandan keyin xato qilganlar soni")),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_progress', to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='vocabulary.word')),
            ],
            options={
                'ordering': ['next_review_at'],
            },
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Boshlanmagan'), ('in_progress', "O'rganilmoqda"), ('completed', 'Tugatildi')], db_index=True, default='not_started', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('time_spent_seconds', models.PositiveIntegerField(default=0)),
                ('completion_percentage', models.PositiveIntegerField(default=0)),
                ('xp_earned', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='content.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['student', 'status'], name='progress_le_student_b67b30_idx'), models.Index(fields=['student', 'completed_at'], name='progress_le_student_125c41_idx')],
                'unique_together': {('student', 'lesson')},
            },
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['student', 'quiz'], name='progress_qu_student_e533a7_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['student', 'completed_at'], name='progress_qu_student_b64ca9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='questionresponse',
            unique_together={('attempt', 'question')},
        ),
        migrations.AddIndex(
            model_name='streak',
            index=models.Index(fields=['current_streak'], name='progress_st_current_243f51_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userachievement',
            unique_together={('student', 'achievement')},
        ),
        migrations.AddIndex(
            model_name='userxp',
            index=models.Index(fields=['-total_xp'], name='progress_us_total_x_fc245f_idx'),
        ),
        migrations.AddIndex(
            model_name='userxp',
            index=models.Index(fields=['-weekly_xp'], name='progress_us_weekly__a67f86_idx'),
        ),
        migrations.AddIndex(
            model_name='wordprogress',
            index=models.Index(fields=['student', 'status'], name='progress_wo_student_44e2ca_idx'),
        ),
        migrations.AddIndex(
            model_name='wordprogress',
            index=models.Index(fields=['student', 'next_review_at'], name='progress_wo_student_bfc04f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='wordprogress',
            unique_together={('student', 'word')},
        ),
    ]
