# Generated by Django 6.0.6 on 2026-06-15 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(db_index=True, help_text="Inglizcha so'z", max_length=100)),
                ('translation_uz', models.CharField(help_text="O'zbekcha tarjima", max_length=200)),
                ('translation_ru', models.CharField(blank=True, help_text='Ruscha tarjima (ixtiyoriy)', max_length=200)),
                ('part_of_speech', models.CharField(choices=[('noun', 'Noun (ot)'), ('verb', "Verb (fe'l)"), ('adjective', 'Adjective (sifat)'), ('adverb', 'Adverb (ravish)'), ('pronoun', 'Pronoun (olmosh)'), ('preposition', 'Preposition (predlog)'), ('conjunction', "Conjunction (bog'lovchi)"), ('interjection', 'Interjection (undov)'), ('phrase', 'Phrase (ibora)'), ('idiom', 'Idiom')], default='noun', max_length=20)),
                ('pronunciation', models.CharField(blank=True, help_text='IPA transkripsiya, masalan: /həˈloʊ/', max_length=200)),
                ('audio_url', models.URLField(blank=True, help_text='Talaffuz audio fayli')),
                ('example_sentence', models.TextField(blank=True, help_text="Inglizcha misol gap (so'z ishlatilgan)")),
                ('example_translation', models.TextField(blank=True, help_text="Misol gapning o'zbekcha tarjimasi")),
                ('cefr_level', models.CharField(blank=True, choices=[('A1', 'A1 — Beginner'), ('A2', 'A2 — Elementary'), ('B1', 'B1 — Intermediate'), ('B2', 'B2 — Upper-Intermediate'), ('C1', 'C1 — Advanced'), ('C2', 'C2 — Proficient')], db_index=True, help_text="Bu so'z qaysi CEFR darajasiga tegishli", max_length=2)),
                ('image', models.ImageField(blank=True, null=True, upload_to='words/')),
                ('notes', models.TextField(blank=True, help_text="Qo'shimcha izoh (qoidalar, sinonimlar)")),
                ('frequency_rank', models.PositiveIntegerField(blank=True, help_text="Eng ko'p uchraydigan 1000 so'z ichidagi reytingi", null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['word'],
                'indexes': [models.Index(fields=['cefr_level'], name='vocabulary__cefr_le_3056db_idx'), models.Index(fields=['part_of_speech'], name='vocabulary__part_of_31e14a_idx'), models.Index(fields=['word'], name='vocabulary__word_7965e8_idx')],
                'constraints': [models.UniqueConstraint(fields=('word', 'part_of_speech', 'translation_uz'), name='unique_word_pos_translation')],
            },
        ),
        migrations.CreateModel(
            name='WordSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('cefr_level', models.CharField(blank=True, choices=[('A1', 'A1 — Beginner'), ('A2', 'A2 — Elementary'), ('B1', 'B1 — Intermediate'), ('B2', 'B2 — Upper-Intermediate'), ('C1', 'C1 — Advanced'), ('C2', 'C2 — Proficient')], max_length=2)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='wordsets/')),
                ('icon', models.CharField(blank=True, max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('words', models.ManyToManyField(blank=True, related_name='word_sets', to='vocabulary.word')),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='LessonWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_key_word', models.BooleanField(default=False, help_text="Bu dars uchun eng muhim so'zlardan biri")),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_words', to='content.lesson')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_appearances', to='vocabulary.word')),
            ],
            options={
                'ordering': ['lesson', 'order'],
                'indexes': [models.Index(fields=['lesson', 'order'], name='vocabulary__lesson__43857d_idx')],
                'unique_together': {('lesson', 'word')},
            },
        ),
    ]
