# Generated by Django 6.0.6 on 2026-06-15 11:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('multiple_choice', "Bitta to'g'ri javob"), ('multiple_select', "Bir nechta to'g'ri javob"), ('true_false', 'True / False'), ('fill_blank', "Bo'sh joyni to'ldirish"), ('matching', 'Juftlash'), ('short_answer', 'Qisqa yozma javob')], default='multiple_choice', max_length=20)),
                ('text', models.TextField(help_text='Savol matni. Fill blank uchun ___ ishlat')),
                ('image', models.ImageField(blank=True, null=True, upload_to='questions/')),
                ('audio_url', models.URLField(blank=True)),
                ('correct_answer_text', models.CharField(blank=True, help_text="Fill blank / Short answer / True-False uchun to'g'ri javob", max_length=500)),
                ('case_sensitive', models.BooleanField(default=False, help_text="Katta-kichik harf farqlansinmi? (asosan bo'lmaydi)")),
                ('explanation', models.TextField(blank=True, help_text="To'g'ri javob nima uchun shu — tushuntirish")),
                ('points', models.PositiveIntegerField(default=1, help_text='Ball')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['quiz', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('assignment_type', models.CharField(choices=[('essay', 'Essay (yozma matn)'), ('short_writing', 'Qisqa yozma javob'), ('speaking', 'Speaking (audio)'), ('translation', 'Tarjima'), ('other', 'Boshqa')], default='essay', max_length=20)),
                ('instructions', models.TextField(help_text="Topshiriqning to'liq matni (Markdown)")),
                ('rubric', models.TextField(blank=True, help_text='Baholash mezonlari (IELTS uchun band descriptors)')),
                ('min_words', models.PositiveIntegerField(blank=True, null=True)),
                ('max_words', models.PositiveIntegerField(blank=True, null=True)),
                ('time_limit_minutes', models.PositiveIntegerField(blank=True, help_text='Vaqt cheklovi (minut)', null=True)),
                ('xp_reward', models.PositiveIntegerField(default=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='content.lesson')),
            ],
            options={
                'ordering': ['lesson', 'order'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, help_text='Yozma javob (essay matni)')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='submissions/audio/')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='submissions/files/')),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('submitted', 'Topshirildi'), ('in_review', 'Tekshirilmoqda'), ('graded', 'Baholandi'), ('returned', 'Qaytarildi (qayta yozish)')], db_index=True, default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=1, help_text='0-100 yoki IELTS band (0-9)', max_digits=4, null=True)),
                ('feedback', models.TextField(blank=True, help_text="O'quvchiga umumiy izoh (Markdown)")),
                ('strengths', models.TextField(blank=True, help_text='Kuchli tomonlari')),
                ('improvements', models.TextField(blank=True, help_text="Yaxshilash kerak bo'lgan joylar")),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='exercises.assignment')),
                ('reviewer', models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_submissions', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quoted_text', models.TextField(blank=True, help_text="'Submission'dan tanlangan parcha")),
                ('start_offset', models.PositiveIntegerField(blank=True, help_text='Matn ichida boshlanish pozitsiyasi', null=True)),
                ('end_offset', models.PositiveIntegerField(blank=True, null=True)),
                ('comment', models.TextField(help_text='Teacher izohi')),
                ('category', models.CharField(choices=[('grammar', 'Grammar'), ('vocabulary', 'Vocabulary'), ('spelling', 'Spelling'), ('structure', 'Structure'), ('style', 'Style'), ('other', 'Other')], default='other', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_comments', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='exercises.assignmentsubmission')),
            ],
            options={
                'ordering': ['submission', 'start_offset', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField(default=False)),
                ('match_pair', models.CharField(blank=True, help_text='Matching savol uchun: juftining belgisi (A, B, 1, 2)', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='exercises.question')),
            ],
            options={
                'ordering': ['question', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('passing_score', models.PositiveIntegerField(default=70, help_text="O'tish uchun minimum foiz", validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('time_limit_seconds', models.PositiveIntegerField(blank=True, help_text="Vaqt cheklovi (sekundlarda). Bo'sh — cheklovsiz.", null=True)),
                ('max_attempts', models.PositiveIntegerField(default=0, help_text='0 = cheksiz. 3 = 3 marta urinish mumkin.')),
                ('shuffle_questions', models.BooleanField(default=True)),
                ('show_correct_answers', models.BooleanField(default=True, help_text="Tugagandan keyin to'g'ri javoblarni ko'rsatish")),
                ('xp_reward', models.PositiveIntegerField(default=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='content.lesson')),
            ],
            options={
                'ordering': ['lesson', 'order'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exercises.quiz'),
        ),
        migrations.AddIndex(
            model_name='assignmentsubmission',
            index=models.Index(fields=['status'], name='exercises_a_status_48dcc3_idx'),
        ),
        migrations.AddIndex(
            model_name='assignmentsubmission',
            index=models.Index(fields=['student', 'status'], name='exercises_a_student_70af26_idx'),
        ),
        migrations.AddIndex(
            model_name='assignmentsubmission',
            index=models.Index(fields=['assignment', 'status'], name='exercises_a_assignm_4eefd9_idx'),
        ),
    ]
