# Generated by Django 6.0.6 on 2026-06-21 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='hint',
            field=models.CharField(blank=True, help_text="Savol qiyin bo'lsa ko'rsatiladigan yordam (ixtiyoriy)", max_length=300),
        ),
    ]
