# Generated by Django 6.0.6 on 2026-06-26 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_question_hint'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='image',
            field=models.ImageField(blank=True, help_text='IELTS Writing Task 1 uchun chart/grafik/diagramma rasmi', null=True, upload_to='assignments/'),
        ),
    ]
